[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/wchorski/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
# (Optional) Text in landing page button
LANDING_BUTTON = ""
# (Optional) Site description on landing page
LANDING_DESCRIPTION = "My Home Lab Wiki"
# (REQUIRED) The Markdown page linked to landing page button (e.g. put home for ./home.md)
LANDING_PAGE = "pywriter"
# (Optional) Site title on landing page
LANDING_TITLE = ""
PYTHON_VERSION = "3.8"
# (REQUIRED) Site repo URL
REPO_URL = "https://github.com/wchorski/obsidian-zola"
# (Optional) Site title in navbar
SITE_TITLE = "Someone's Second ðŸ§ "
# (Optional) Site title in browser tab (leave blank to use SITE_TITLE)
SITE_TITLE_TAB = ""
# (REQUIRED) Netlify site URL
SITE_URL = ""
# (Optional) Site Timezone
TIMEZONE = "America/Chicago"
ZOLA_VERSION = "0.15.2"
# (Optional, default title) How to sort notes inside each section on the right sidebar ("date" or "title"). Subsections on side bar are sorted by title, the sort order cannot be changed.
SORT_BY = "title"
# (Optional) Google Analytics Measurement ID
GANALYTICS = ""
# (Optional, default true) Slugify URLs. Put "" to disable.
SLUGIFY = "y"
# (Optional, default true) Shows knowledge graph on home page. Put "" to disable.
HOME_GRAPH = "y"
# (Optional, default true) Shows knowledge graph on every page. Put "" to disable.
PAGE_GRAPH = "y"
# (Optional, default false) Whether sidebar sections should be collapsed by default.
SIDEBAR_COLLAPSED = "true"
# (Optional, default blank) Additional footer content.
FOOTER = "Â© William Chorski"
# (Optional, default main) Root section name.
ROOT_SECTION_NAME = "main"
# (Optional) visjs graph options. Can remove if desired.
GRAPH_OPTIONS = """
        {
        	nodes: {
        		shape: "dot",
        		color: isDark() ? "#8c8e91" : "#e4e0d8",
        		font: {
        			face: "Inter",
        			color: isDark() ? "#d6ad60" : "#d6ad60",
        			strokeColor: isDark() ? "#d6ad60" : "#d6ad60",
        		},
        		scaling: {
        			label: {
        				enabled: true,
        			},
        		},
        	},
        	edges: {
        		color: { inherit: "both" },
        		width: 0.8,
        		smooth: {
        			type: "continuous",
        		},
        		hoverWidth: 4,
        	},
        	interaction: {
        		hover: true,
        	},
        	height: "100%",
        	width: "100%",
        	physics: {
        		solver: "repulsion",
        	},
        }
        """